[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "stack"
version = "0.0.2"

[tool.hatch.build.targets.wheel]
packages = ["C:/Development/PythonProject/PythonProject"]